title: Roweryskladane.pl
description: "Pasjonujemy się rowerami, a składane to coraz popularniejsze połączenie przyjemności z jazdy, miejskiej mobilności i wyjątkowego stylu. Piszemy, jeździmy i opowiadamy o mikrokosmosie rowerów składanych."
name: Roweryskladane.pl
locale: pl-PL
timezone: Europe/Warsaw

atom_feed:
  hide: true

footer:
  links: []

lang: pl

# Ważne dla GitHub Pages:
# Na github.io URL jest stały, a baseurl musi być nazwą repo.
url: https://jraczka-anty.github.io
baseurl: /Roweryskladane.pl

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: air

logo: /assets/logo.png

search: false
breadcrumbs: false

collections:
  projects:
    output: true
    permalink: /projekty/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: projects
    values:
      layout: single

# Blog (posts)
permalink: /journal/:categories/:title/

custom_css:
  - /assets/css/custom.css
